// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_logs.sql

package repo

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminLogs = `-- name: CountAdminLogs :one
SELECT COUNT(*) FROM admin_logs al
JOIN users u ON al.admin_id = u.id
WHERE ($1 = '' OR al.action ILIKE '%' || $1 || '%' OR u.full_name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
  AND ($2 = '' OR al.action = $2)
  AND ($3 = '' OR al.target_type = $3)
`

type CountAdminLogsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) CountAdminLogs(ctx context.Context, arg CountAdminLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminLogs, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAdminLogs = `-- name: ListAdminLogs :many
SELECT 
    al.id,
    al.admin_id,
    al.action,
    al.target_type,
    al.target_id,
    al.details,
    al.ip_address,
    al.created_at,
    u.full_name AS admin_name,
    u.email AS admin_email
FROM admin_logs al
JOIN users u ON al.admin_id = u.id
WHERE ($1 = '' OR al.action ILIKE '%' || $1 || '%' OR u.full_name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
  AND ($2 = '' OR al.action = $2)
  AND ($3 = '' OR al.target_type = $3)
ORDER BY al.created_at DESC
LIMIT $4 OFFSET $5
`

type ListAdminLogsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAdminLogsRow struct {
	ID         uuid.UUID        `json:"id"`
	AdminID    uuid.UUID        `json:"admin_id"`
	Action     *string          `json:"action"`
	TargetType *string          `json:"target_type"`
	TargetID   *uuid.UUID       `json:"target_id"`
	Details    []byte           `json:"details"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	AdminName  string           `json:"admin_name"`
	AdminEmail string           `json:"admin_email"`
}

func (q *Queries) ListAdminLogs(ctx context.Context, arg ListAdminLogsParams) ([]ListAdminLogsRow, error) {
	rows, err := q.db.Query(ctx, listAdminLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLogsRow{}
	for rows.Next() {
		var i ListAdminLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.AdminName,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
