// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package repo

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date,capacity_range)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at
`

type CreateEventParams struct {
	OrganizerID    uuid.UUID                  `json:"organizer_id"`
	Title          string                     `json:"title"`
	Slug           string                     `json:"slug"`
	Description    string                     `json:"description"`
	Venue          string                     `json:"venue"`
	City           string                     `json:"city"`
	StartDate      time.Time                  `json:"start_date"`
	EndDate        *time.Time                 `json:"end_date"`
	StartTime      *string                    `json:"start_time"`
	EndTime        *string                    `json:"end_time"`
	CoverImageUrl  string                     `json:"cover_image_url"`
	Status         EventStatus                `json:"status"`
	SalesStartDate *time.Time                 `json:"sales_start_date"`
	SalesEndDate   *time.Time                 `json:"sales_end_date"`
	CapacityRange  *pgtype.Range[pgtype.Int4] `json:"capacity_range"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.City,
		arg.StartDate,
		arg.EndDate,
		arg.StartTime,
		arg.EndTime,
		arg.CoverImageUrl,
		arg.Status,
		arg.SalesStartDate,
		arg.SalesEndDate,
		arg.CapacityRange,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteEventsByOrganizer = `-- name: DeleteEventsByOrganizer :exec
DELETE FROM events
WHERE organizer_id = $1
`

func (q *Queries) DeleteEventsByOrganizer(ctx context.Context, organizerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventsByOrganizer, organizerID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at FROM events 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByIDPublic = `-- name: GetEventByIDPublic :one
SELECT 
    id, organizer_id, title, slug, description, venue, city,
    start_date, end_date, start_time, end_time, cover_image_url,
    status, sales_start_date, sales_end_date,capacity_range, created_at, updated_at
FROM events
WHERE id = $1 AND status = 'published'
`

func (q *Queries) GetEventByIDPublic(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIDPublic, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlugPublic = `-- name: GetEventBySlugPublic :one
SELECT 
    id, organizer_id, title, slug, description, venue, city,
    start_date, end_date, start_time, end_time, cover_image_url,
    status, sales_start_date, sales_end_date, created_at, updated_at
FROM events
WHERE slug = $1 AND status = 'published'
`

type GetEventBySlugPublicRow struct {
	ID             uuid.UUID        `json:"id"`
	OrganizerID    uuid.UUID        `json:"organizer_id"`
	Title          string           `json:"title"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Venue          string           `json:"venue"`
	City           string           `json:"city"`
	StartDate      time.Time        `json:"start_date"`
	EndDate        *time.Time       `json:"end_date"`
	StartTime      *string          `json:"start_time"`
	EndTime        *string          `json:"end_time"`
	CoverImageUrl  string           `json:"cover_image_url"`
	Status         EventStatus      `json:"status"`
	SalesStartDate *time.Time       `json:"sales_start_date"`
	SalesEndDate   *time.Time       `json:"sales_end_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetEventBySlugPublic(ctx context.Context, slug string) (GetEventBySlugPublicRow, error) {
	row := q.db.QueryRow(ctx, getEventBySlugPublic, slug)
	var i GetEventBySlugPublicRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsBySlug = `-- name: GetEventsBySlug :one
SELECT id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at FROM events 
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetEventsBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventsBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.organizer_id, e.title, e.slug, e.description, e.venue, e.city, e.start_date, e.end_date, e.start_time, e.end_time, e.cover_image_url, e.status, e.sales_start_date, e.sales_end_date, e.capacity_range, e.created_at, e.updated_at, u.role FROM events e, users u 
where u.role = $1
ORDER BY start_date ASC, start_time ASC
`

type ListEventsRow struct {
	ID             uuid.UUID                  `json:"id"`
	OrganizerID    uuid.UUID                  `json:"organizer_id"`
	Title          string                     `json:"title"`
	Slug           string                     `json:"slug"`
	Description    string                     `json:"description"`
	Venue          string                     `json:"venue"`
	City           string                     `json:"city"`
	StartDate      time.Time                  `json:"start_date"`
	EndDate        *time.Time                 `json:"end_date"`
	StartTime      *string                    `json:"start_time"`
	EndTime        *string                    `json:"end_time"`
	CoverImageUrl  string                     `json:"cover_image_url"`
	Status         EventStatus                `json:"status"`
	SalesStartDate *time.Time                 `json:"sales_start_date"`
	SalesEndDate   *time.Time                 `json:"sales_end_date"`
	CapacityRange  *pgtype.Range[pgtype.Int4] `json:"capacity_range"`
	CreatedAt      pgtype.Timestamp           `json:"created_at"`
	UpdatedAt      pgtype.Timestamp           `json:"updated_at"`
	Role           UserRole                   `json:"role"`
}

func (q *Queries) ListEvents(ctx context.Context, role UserRole) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.City,
			&i.StartDate,
			&i.EndDate,
			&i.StartTime,
			&i.EndTime,
			&i.CoverImageUrl,
			&i.Status,
			&i.SalesStartDate,
			&i.SalesEndDate,
			&i.CapacityRange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCity = `-- name: ListEventsByCity :many
SELECT id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at FROM events 
WHERE city ILIKE $1
ORDER BY start_date ASC, start_time ASC
`

func (q *Queries) ListEventsByCity(ctx context.Context, city string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.City,
			&i.StartDate,
			&i.EndDate,
			&i.StartTime,
			&i.EndTime,
			&i.CoverImageUrl,
			&i.Status,
			&i.SalesStartDate,
			&i.SalesEndDate,
			&i.CapacityRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrganizer = `-- name: ListEventsByOrganizer :many
SELECT id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at FROM events 
WHERE organizer_id = $1
ORDER BY start_date DESC, start_time DESC
`

func (q *Queries) ListEventsByOrganizer(ctx context.Context, organizerID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrganizer, organizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.City,
			&i.StartDate,
			&i.EndDate,
			&i.StartTime,
			&i.EndTime,
			&i.CoverImageUrl,
			&i.Status,
			&i.SalesStartDate,
			&i.SalesEndDate,
			&i.CapacityRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByStatus = `-- name: ListEventsByStatus :many
SELECT id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at FROM events 
WHERE status = $1
ORDER BY start_date ASC, start_time ASC
`

func (q *Queries) ListEventsByStatus(ctx context.Context, status EventStatus) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.City,
			&i.StartDate,
			&i.EndDate,
			&i.StartTime,
			&i.EndTime,
			&i.CoverImageUrl,
			&i.Status,
			&i.SalesStartDate,
			&i.SalesEndDate,
			&i.CapacityRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partialEventUpdate = `-- name: PartialEventUpdate :one
UPDATE events
SET
    title = COALESCE($3, title),
    slug = COALESCE($4, slug),
    description = COALESCE($5, description),
    venue = COALESCE($6, venue),
    city = COALESCE($7, city),
    start_date = COALESCE($8, start_date),
    end_date = COALESCE($9, end_date),
    start_time = COALESCE($10, start_time),
    end_time = COALESCE($11, end_time),
    cover_image_url = COALESCE($12, cover_image_url),
    status = COALESCE($13, status),
    sales_start_date = COALESCE($14, sales_start_date),
    sales_end_date = COALESCE($15, sales_end_date),
    capacity_range = COALESCE($16, capacity_range),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND organizer_id = $2
RETURNING id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at
`

type PartialEventUpdateParams struct {
	ID             uuid.UUID                  `json:"id"`
	OrganizerID    uuid.UUID                  `json:"organizer_id"`
	Title          *string                    `json:"title"`
	Slug           *string                    `json:"slug"`
	Description    string                     `json:"description"`
	Venue          string                     `json:"venue"`
	City           *string                    `json:"city"`
	StartDate      *time.Time                 `json:"start_date"`
	EndDate        *time.Time                 `json:"end_date"`
	StartTime      *string                    `json:"start_time"`
	EndTime        *string                    `json:"end_time"`
	CoverImageUrl  string                     `json:"cover_image_url"`
	Status         *EventStatus               `json:"status"`
	SalesStartDate *time.Time                 `json:"sales_start_date"`
	SalesEndDate   *time.Time                 `json:"sales_end_date"`
	CapacityRange  *pgtype.Range[pgtype.Int4] `json:"capacity_range"`
}

func (q *Queries) PartialEventUpdate(ctx context.Context, arg PartialEventUpdateParams) (Event, error) {
	row := q.db.QueryRow(ctx, partialEventUpdate,
		arg.ID,
		arg.OrganizerID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.City,
		arg.StartDate,
		arg.EndDate,
		arg.StartTime,
		arg.EndTime,
		arg.CoverImageUrl,
		arg.Status,
		arg.SalesStartDate,
		arg.SalesEndDate,
		arg.CapacityRange,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, slug = $3, description = $4, venue = $5, city = $6, start_date = $7, end_date = $8, start_time = $9, end_time = $10, cover_image_url = $11, status = $12, sales_start_date = $13, sales_end_date = $14, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at
`

type UpdateEventParams struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Slug           string      `json:"slug"`
	Description    string      `json:"description"`
	Venue          string      `json:"venue"`
	City           string      `json:"city"`
	StartDate      time.Time   `json:"start_date"`
	EndDate        *time.Time  `json:"end_date"`
	StartTime      *string     `json:"start_time"`
	EndTime        *string     `json:"end_time"`
	CoverImageUrl  string      `json:"cover_image_url"`
	Status         EventStatus `json:"status"`
	SalesStartDate *time.Time  `json:"sales_start_date"`
	SalesEndDate   *time.Time  `json:"sales_end_date"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.City,
		arg.StartDate,
		arg.EndDate,
		arg.StartTime,
		arg.EndTime,
		arg.CoverImageUrl,
		arg.Status,
		arg.SalesStartDate,
		arg.SalesEndDate,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventCoverImage = `-- name: UpdateEventCoverImage :one
UPDATE events
SET cover_image_url = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at
`

type UpdateEventCoverImageParams struct {
	ID            uuid.UUID `json:"id"`
	CoverImageUrl string    `json:"cover_image_url"`
}

func (q *Queries) UpdateEventCoverImage(ctx context.Context, arg UpdateEventCoverImageParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventCoverImage, arg.ID, arg.CoverImageUrl)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organizer_id, title, slug, description, venue, city, start_date, end_date, start_time, end_time, cover_image_url, status, sales_start_date, sales_end_date, capacity_range, created_at, updated_at
`

type UpdateEventStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status EventStatus `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus, arg.ID, arg.Status)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.City,
		&i.StartDate,
		&i.EndDate,
		&i.StartTime,
		&i.EndTime,
		&i.CoverImageUrl,
		&i.Status,
		&i.SalesStartDate,
		&i.SalesEndDate,
		&i.CapacityRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
