// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repo

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email,
    quantity, unit_price, total_amount, payment_status, transaction_id,
    manual_code, qr_code_hash, qr_code_plaintext, qr_code_image_url,
    device_info, ip_address, platform_fee
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at
`

type CreateOrderParams struct {
	EventID         uuid.UUID     `json:"event_id"`
	TicketTypeID    uuid.UUID     `json:"ticket_type_id"`
	AttendeeName    string        `json:"attendee_name"`
	AttendeePhone   string        `json:"attendee_phone"`
	AttendeeEmail   *string       `json:"attendee_email"`
	Quantity        int32         `json:"quantity"`
	UnitPrice       int32         `json:"unit_price"`
	TotalAmount     int32         `json:"total_amount"`
	PaymentStatus   PaymentStatus `json:"payment_status"`
	TransactionID   *string       `json:"transaction_id"`
	ManualCode      string        `json:"manual_code"`
	QrCodeHash      string        `json:"qr_code_hash"`
	QrCodePlaintext string        `json:"qr_code_plaintext"`
	QrCodeImageUrl  string        `json:"qr_code_image_url"`
	DeviceInfo      string        `json:"device_info"`
	IpAddress       *netip.Addr   `json:"ip_address"`
	PlatformFee     int32         `json:"platform_fee"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.EventID,
		arg.TicketTypeID,
		arg.AttendeeName,
		arg.AttendeePhone,
		arg.AttendeeEmail,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.PaymentStatus,
		arg.TransactionID,
		arg.ManualCode,
		arg.QrCodeHash,
		arg.QrCodePlaintext,
		arg.QrCodeImageUrl,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.PlatformFee,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.ManualCode,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const decrementTicketQuantity = `-- name: DecrementTicketQuantity :execrows
UPDATE ticket_types
SET quantity_available = quantity_available - $2,
    quantity_sold = quantity_sold + $2
WHERE id = $1 AND quantity_available >= $2
`

type DecrementTicketQuantityParams struct {
	ID                uuid.UUID `json:"id"`
	QuantityAvailable int32     `json:"quantity_available"`
}

func (q *Queries) DecrementTicketQuantity(ctx context.Context, arg DecrementTicketQuantityParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementTicketQuantity, arg.ID, arg.QuantityAvailable)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventAnalytics = `-- name: GetEventAnalytics :one
SELECT
    COUNT(*) AS paid_orders,
    COALESCE(SUM(total_amount - platform_fee), 0) AS net_revenue,
    COUNT(*) FILTER (WHERE is_used = TRUE) AS checked_in_count
FROM orders
WHERE event_id = $1 AND payment_status = 'paid'
`

type GetEventAnalyticsRow struct {
	PaidOrders     int64       `json:"paid_orders"`
	NetRevenue     interface{} `json:"net_revenue"`
	CheckedInCount int64       `json:"checked_in_count"`
}

func (q *Queries) GetEventAnalytics(ctx context.Context, eventID uuid.UUID) (GetEventAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getEventAnalytics, eventID)
	var i GetEventAnalyticsRow
	err := row.Scan(&i.PaidOrders, &i.NetRevenue, &i.CheckedInCount)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.ManualCode,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByManualCode = `-- name: GetOrderByManualCode :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders
WHERE manual_code = $1
`

func (q *Queries) GetOrderByManualCode(ctx context.Context, manualCode string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByManualCode, manualCode)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.ManualCode,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByQRHash = `-- name: GetOrderByQRHash :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders
WHERE qr_code_hash = $1
`

func (q *Queries) GetOrderByQRHash(ctx context.Context, qrCodeHash string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByQRHash, qrCodeHash)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.ManualCode,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByTransactionID = `-- name: GetOrderByTransactionID :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders 
WHERE transaction_id = $1
`

func (q *Queries) GetOrderByTransactionID(ctx context.Context, transactionID *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByTransactionID, transactionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.ManualCode,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAnalytics = `-- name: GetPlatformAnalytics :one
SELECT
    COUNT(DISTINCT u.id) AS total_users,
    COUNT(DISTINCT e.id) AS total_events,
    COUNT(o.id) AS total_orders,
    COALESCE(SUM(o.total_amount), 0) AS gross_revenue,
    COALESCE(SUM(o.platform_fee), 0) AS total_platform_fee,
    COALESCE(SUM(o.total_amount - o.platform_fee), 0) AS net_revenue,
    COUNT(o.id) FILTER (WHERE o.is_used = TRUE) AS total_checked_in
FROM users u
JOIN events e ON e.organizer_id = u.id
LEFT JOIN orders o ON o.event_id = e.id AND o.payment_status = 'paid'
`

type GetPlatformAnalyticsRow struct {
	TotalUsers       int64       `json:"total_users"`
	TotalEvents      int64       `json:"total_events"`
	TotalOrders      int64       `json:"total_orders"`
	GrossRevenue     interface{} `json:"gross_revenue"`
	TotalPlatformFee interface{} `json:"total_platform_fee"`
	NetRevenue       interface{} `json:"net_revenue"`
	TotalCheckedIn   int64       `json:"total_checked_in"`
}

func (q *Queries) GetPlatformAnalytics(ctx context.Context) (GetPlatformAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAnalytics)
	var i GetPlatformAnalyticsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalEvents,
		&i.TotalOrders,
		&i.GrossRevenue,
		&i.TotalPlatformFee,
		&i.NetRevenue,
		&i.TotalCheckedIn,
	)
	return i, err
}

const insertWebhookLog = `-- name: InsertWebhookLog :one
INSERT INTO webhook_logs (
    gateway, payload, headers, signature_valid, processed,error_message, received_at
) VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
RETURNING id, gateway, payload, headers, signature_valid, processed, processed_at, error_message, received_at
`

type InsertWebhookLogParams struct {
	Gateway        string `json:"gateway"`
	Payload        []byte `json:"payload"`
	Headers        []byte `json:"headers"`
	SignatureValid *bool  `json:"signature_valid"`
	Processed      *bool  `json:"processed"`
	ErrorMessage   string `json:"error_message"`
}

func (q *Queries) InsertWebhookLog(ctx context.Context, arg InsertWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, insertWebhookLog,
		arg.Gateway,
		arg.Payload,
		arg.Headers,
		arg.SignatureValid,
		arg.Processed,
		arg.ErrorMessage,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.Payload,
		&i.Headers,
		&i.SignatureValid,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.ReceivedAt,
	)
	return i, err
}

const listAllTransactions = `-- name: ListAllTransactions :many
SELECT o.id AS order_id, e.title AS event_title, o.attendee_name, o.total_amount AS amount, o.payment_status, o.created_at
FROM orders o
JOIN events e ON o.event_id = e.id
WHERE ($1::text = '' OR o.payment_status = $1::payment_status)
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR o.event_id = $2::uuid)
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAllTransactionsParams struct {
	Column1 string    `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListAllTransactionsRow struct {
	OrderID       uuid.UUID        `json:"order_id"`
	EventTitle    string           `json:"event_title"`
	AttendeeName  string           `json:"attendee_name"`
	Amount        int32            `json:"amount"`
	PaymentStatus PaymentStatus    `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListAllTransactions(ctx context.Context, arg ListAllTransactionsParams) ([]ListAllTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listAllTransactions,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTransactionsRow{}
	for rows.Next() {
		var i ListAllTransactionsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.EventTitle,
			&i.AttendeeName,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendeesByEvent = `-- name: ListAttendeesByEvent :many
SELECT o.id, o.attendee_name, o.attendee_phone, o.attendee_email, o.quantity, o.unit_price, o.total_amount, o.is_used, o.used_at, o.created_at, tt.name AS ticket_type_name
FROM orders o
JOIN ticket_types tt ON o.ticket_type_id = tt.id
WHERE o.event_id = $1 AND o.payment_status = 'paid'
ORDER BY o.created_at DESC
`

type ListAttendeesByEventRow struct {
	ID             uuid.UUID        `json:"id"`
	AttendeeName   string           `json:"attendee_name"`
	AttendeePhone  string           `json:"attendee_phone"`
	AttendeeEmail  *string          `json:"attendee_email"`
	Quantity       int32            `json:"quantity"`
	UnitPrice      int32            `json:"unit_price"`
	TotalAmount    int32            `json:"total_amount"`
	IsUsed         bool             `json:"is_used"`
	UsedAt         pgtype.Timestamp `json:"used_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	TicketTypeName string           `json:"ticket_type_name"`
}

func (q *Queries) ListAttendeesByEvent(ctx context.Context, eventID uuid.UUID) ([]ListAttendeesByEventRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesByEventRow{}
	for rows.Next() {
		var i ListAttendeesByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.AttendeeName,
			&i.AttendeePhone,
			&i.AttendeeEmail,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.IsUsed,
			&i.UsedAt,
			&i.CreatedAt,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckinHistoryByEvent = `-- name: ListCheckinHistoryByEvent :many
SELECT id AS order_id, attendee_name, attendee_phone, used_at
FROM orders
WHERE event_id = $1 AND is_used = TRUE
ORDER BY used_at DESC
LIMIT $2 OFFSET $3
`

type ListCheckinHistoryByEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListCheckinHistoryByEventRow struct {
	OrderID       uuid.UUID        `json:"order_id"`
	AttendeeName  string           `json:"attendee_name"`
	AttendeePhone string           `json:"attendee_phone"`
	UsedAt        pgtype.Timestamp `json:"used_at"`
}

func (q *Queries) ListCheckinHistoryByEvent(ctx context.Context, arg ListCheckinHistoryByEventParams) ([]ListCheckinHistoryByEventRow, error) {
	rows, err := q.db.Query(ctx, listCheckinHistoryByEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinHistoryByEventRow{}
	for rows.Next() {
		var i ListCheckinHistoryByEventRow
		if err := rows.Scan(
			&i.OrderID,
			&i.AttendeeName,
			&i.AttendeePhone,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderByEvent = `-- name: ListOrderByEvent :many
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrderByEvent(ctx context.Context, eventID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrderByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TicketTypeID,
			&i.AttendeeName,
			&i.AttendeePhone,
			&i.AttendeeEmail,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.TransactionID,
			&i.PaymentReceivedAt,
			&i.PaymentWebhookReceived,
			&i.QrCodeHash,
			&i.QrCodeImageUrl,
			&i.QrCodePlaintext,
			&i.ManualCode,
			&i.IsUsed,
			&i.UsedAt,
			&i.CheckedInBy,
			&i.PlatformFee,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderUsed = `-- name: MarkOrderUsed :exec
UPDATE orders 
SET is_used = TRUE, used_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_used = FALSE
`

func (q *Queries) MarkOrderUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOrderUsed, id)
	return err
}

const updateOrderPayment = `-- name: UpdateOrderPayment :exec
UPDATE orders
SET
    payment_status = $2,
    transaction_id = $3,
    payment_received_at = CURRENT_TIMESTAMP,
    payment_webhook_received = TRUE
WHERE id = $1
RETURNING id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, manual_code, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at
`

type UpdateOrderPaymentParams struct {
	ID            uuid.UUID     `json:"id"`
	PaymentStatus PaymentStatus `json:"payment_status"`
	TransactionID *string       `json:"transaction_id"`
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, updateOrderPayment, arg.ID, arg.PaymentStatus, arg.TransactionID)
	return err
}

const updateOrderQRCode = `-- name: UpdateOrderQRCode :exec
UPDATE orders
SET qr_code_hash = $2, qr_code_image_url = $3
WHERE id = $1
`

type UpdateOrderQRCodeParams struct {
	ID             uuid.UUID `json:"id"`
	QrCodeHash     string    `json:"qr_code_hash"`
	QrCodeImageUrl string    `json:"qr_code_image_url"`
}

func (q *Queries) UpdateOrderQRCode(ctx context.Context, arg UpdateOrderQRCodeParams) error {
	_, err := q.db.Exec(ctx, updateOrderQRCode, arg.ID, arg.QrCodeHash, arg.QrCodeImageUrl)
	return err
}

const updateOrderQRImage = `-- name: UpdateOrderQRImage :exec
UPDATE orders
SET qr_code_image_url = $2
WHERE id = $1
`

type UpdateOrderQRImageParams struct {
	ID             uuid.UUID `json:"id"`
	QrCodeImageUrl string    `json:"qr_code_image_url"`
}

func (q *Queries) UpdateOrderQRImage(ctx context.Context, arg UpdateOrderQRImageParams) error {
	_, err := q.db.Exec(ctx, updateOrderQRImage, arg.ID, arg.QrCodeImageUrl)
	return err
}

const getDailySales = `-- name: GetDailySales :many
SELECT DATE(o.created_at) AS sale_date, COUNT(*)::int AS tickets, SUM(o.total_amount)::int AS revenue
FROM orders o
WHERE o.event_id = $1 AND o.payment_status = 'paid'
GROUP BY DATE(o.created_at)
ORDER BY sale_date
`

type GetDailySalesRow struct {
	SaleDate pgtype.Date `json:"sale_date"`
	Tickets  int32       `json:"tickets"`
	Revenue  int32       `json:"revenue"`
}

func (q *Queries) GetDailySales(ctx context.Context, eventID uuid.UUID) ([]GetDailySalesRow, error) {
	rows, err := q.db.Query(ctx, getDailySales, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySalesRow{}
	for rows.Next() {
		var i GetDailySalesRow
		if err := rows.Scan(&i.SaleDate, &i.Tickets, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketTypeBreakdown = `-- name: GetTicketTypeBreakdown :many
SELECT tt.name, COUNT(*)::int AS sold, SUM(o.total_amount)::int AS revenue
FROM orders o
JOIN ticket_types tt ON o.ticket_type_id = tt.id
WHERE o.event_id = $1 AND o.payment_status = 'paid'
GROUP BY tt.name
`

type GetTicketTypeBreakdownRow struct {
	Name    string `json:"name"`
	Sold    int32  `json:"sold"`
	Revenue int32  `json:"revenue"`
}

func (q *Queries) GetTicketTypeBreakdown(ctx context.Context, eventID uuid.UUID) ([]GetTicketTypeBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getTicketTypeBreakdown, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketTypeBreakdownRow{}
	for rows.Next() {
		var i GetTicketTypeBreakdownRow
		if err := rows.Scan(&i.Name, &i.Sold, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
