// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repo

import (
	"context"

	uuid "github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email,
    quantity, unit_price, total_amount, payment_status, transaction_id, qr_code_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, device_info, ip_address, created_at
`

type CreateOrderParams struct {
	EventID       uuid.UUID     `json:"event_id"`
	TicketTypeID  uuid.UUID     `json:"ticket_type_id"`
	AttendeeName  string        `json:"attendee_name"`
	AttendeePhone string        `json:"attendee_phone"`
	AttendeeEmail *string       `json:"attendee_email"`
	Quantity      int32         `json:"quantity"`
	UnitPrice     int32         `json:"unit_price"`
	TotalAmount   int32         `json:"total_amount"`
	PaymentStatus PaymentStatus `json:"payment_status"`
	TransactionID *string       `json:"transaction_id"`
	QrCodeHash    string        `json:"qr_code_hash"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.EventID,
		arg.TicketTypeID,
		arg.AttendeeName,
		arg.AttendeePhone,
		arg.AttendeeEmail,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.PaymentStatus,
		arg.TransactionID,
		arg.QrCodeHash,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
