// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repo

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email,
    quantity, unit_price, total_amount, payment_status, transaction_id,
    qr_code_hash, qr_code_plaintext, qr_code_image_url,
    device_info, ip_address, platform_fee
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at
`

type CreateOrderParams struct {
	EventID         uuid.UUID     `json:"event_id"`
	TicketTypeID    uuid.UUID     `json:"ticket_type_id"`
	AttendeeName    string        `json:"attendee_name"`
	AttendeePhone   string        `json:"attendee_phone"`
	AttendeeEmail   *string       `json:"attendee_email"`
	Quantity        int32         `json:"quantity"`
	UnitPrice       int32         `json:"unit_price"`
	TotalAmount     int32         `json:"total_amount"`
	PaymentStatus   PaymentStatus `json:"payment_status"`
	TransactionID   *string       `json:"transaction_id"`
	QrCodeHash      string        `json:"qr_code_hash"`
	QrCodePlaintext string        `json:"qr_code_plaintext"`
	QrCodeImageUrl  string        `json:"qr_code_image_url"`
	DeviceInfo      string        `json:"device_info"`
	IpAddress       *netip.Addr   `json:"ip_address"`
	PlatformFee     int32         `json:"platform_fee"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.EventID,
		arg.TicketTypeID,
		arg.AttendeeName,
		arg.AttendeePhone,
		arg.AttendeeEmail,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.PaymentStatus,
		arg.TransactionID,
		arg.QrCodeHash,
		arg.QrCodePlaintext,
		arg.QrCodeImageUrl,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.PlatformFee,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const decrementTicketQuantity = `-- name: DecrementTicketQuantity :execrows
UPDATE ticket_types
SET quantity_available = quantity_available - $2,
    quantity_sold = quantity_sold + $2
WHERE id = $1 AND quantity_available >= $2
`

type DecrementTicketQuantityParams struct {
	ID                uuid.UUID `json:"id"`
	QuantityAvailable int32     `json:"quantity_available"`
}

func (q *Queries) DecrementTicketQuantity(ctx context.Context, arg DecrementTicketQuantityParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementTicketQuantity, arg.ID, arg.QuantityAvailable)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByQRHash = `-- name: GetOrderByQRHash :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders
WHERE qr_code_hash = $1
`

func (q *Queries) GetOrderByQRHash(ctx context.Context, qrCodeHash string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByQRHash, qrCodeHash)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByTransactionID = `-- name: GetOrderByTransactionID :one
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders 
WHERE transaction_id = $1
`

func (q *Queries) GetOrderByTransactionID(ctx context.Context, transactionID *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByTransactionID, transactionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeName,
		&i.AttendeePhone,
		&i.AttendeeEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaymentReceivedAt,
		&i.PaymentWebhookReceived,
		&i.QrCodeHash,
		&i.QrCodeImageUrl,
		&i.QrCodePlaintext,
		&i.IsUsed,
		&i.UsedAt,
		&i.CheckedInBy,
		&i.PlatformFee,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookLog = `-- name: InsertWebhookLog :one
INSERT INTO webhook_logs (
    gateway, payload, headers, signature_valid, processed,error_message, received_at
) VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
RETURNING id, gateway, payload, headers, signature_valid, processed, processed_at, error_message, received_at
`

type InsertWebhookLogParams struct {
	Gateway        string `json:"gateway"`
	Payload        []byte `json:"payload"`
	Headers        []byte `json:"headers"`
	SignatureValid *bool  `json:"signature_valid"`
	Processed      *bool  `json:"processed"`
	ErrorMessage   string `json:"error_message"`
}

func (q *Queries) InsertWebhookLog(ctx context.Context, arg InsertWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, insertWebhookLog,
		arg.Gateway,
		arg.Payload,
		arg.Headers,
		arg.SignatureValid,
		arg.Processed,
		arg.ErrorMessage,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.Payload,
		&i.Headers,
		&i.SignatureValid,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.ReceivedAt,
	)
	return i, err
}

const listOrderByEvent = `-- name: ListOrderByEvent :many
SELECT id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at FROM orders
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrderByEvent(ctx context.Context, eventID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrderByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TicketTypeID,
			&i.AttendeeName,
			&i.AttendeePhone,
			&i.AttendeeEmail,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.TransactionID,
			&i.PaymentReceivedAt,
			&i.PaymentWebhookReceived,
			&i.QrCodeHash,
			&i.QrCodeImageUrl,
			&i.QrCodePlaintext,
			&i.IsUsed,
			&i.UsedAt,
			&i.CheckedInBy,
			&i.PlatformFee,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPayment = `-- name: UpdateOrderPayment :exec
UPDATE orders
SET
    payment_status = $2,
    transaction_id = $3,
    payment_received_at = CURRENT_TIMESTAMP,
    payment_webhook_received = TRUE
WHERE id = $1
RETURNING id, event_id, ticket_type_id, attendee_name, attendee_phone, attendee_email, quantity, unit_price, total_amount, payment_status, payment_method, transaction_id, payment_received_at, payment_webhook_received, qr_code_hash, qr_code_image_url, qr_code_plaintext, is_used, used_at, checked_in_by, platform_fee, device_info, ip_address, created_at
`

type UpdateOrderPaymentParams struct {
	ID            uuid.UUID     `json:"id"`
	PaymentStatus PaymentStatus `json:"payment_status"`
	TransactionID *string       `json:"transaction_id"`
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, updateOrderPayment, arg.ID, arg.PaymentStatus, arg.TransactionID)
	return err
}

const updateOrderQRCode = `-- name: UpdateOrderQRCode :exec
UPDATE orders
SET qr_code_hash = $2, qr_code_image_url = $3
WHERE id = $1
`

type UpdateOrderQRCodeParams struct {
	ID             uuid.UUID `json:"id"`
	QrCodeHash     string    `json:"qr_code_hash"`
	QrCodeImageUrl string    `json:"qr_code_image_url"`
}

func (q *Queries) UpdateOrderQRCode(ctx context.Context, arg UpdateOrderQRCodeParams) error {
	_, err := q.db.Exec(ctx, updateOrderQRCode, arg.ID, arg.QrCodeHash, arg.QrCodeImageUrl)
	return err
}

const updateOrderQRImage = `-- name: UpdateOrderQRImage :exec
UPDATE orders
SET qr_code_image_url = $2
WHERE id = $1
`

type UpdateOrderQRImageParams struct {
	ID             uuid.UUID `json:"id"`
	QrCodeImageUrl string    `json:"qr_code_image_url"`
}

func (q *Queries) UpdateOrderQRImage(ctx context.Context, arg UpdateOrderQRImageParams) error {
	_, err := q.db.Exec(ctx, updateOrderQRImage, arg.ID, arg.QrCodeImageUrl)
	return err
}
