// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id uuid.UUID) error
	DeleteEventsByOrganizer(ctx context.Context, organizerID uuid.UUID) error
	GetEventByID(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventsBySlug(ctx context.Context, slug string) (Event, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsByCity(ctx context.Context, city string) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, organizerID uuid.UUID) ([]Event, error)
	ListEventsByStatus(ctx context.Context, status EventStatus) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	updateEventCoverImage(ctx context.Context, arg updateEventCoverImageParams) (Event, error)
	updateEventStatus(ctx context.Context, arg updateEventStatusParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
