// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package repo

import (
	"context"

	uuid "github.com/google/uuid"
)

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (event_id, name, description, price, quantity_available, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, name, description, price, quantity_available, quantity_sold, is_active, created_at
`

type CreateTicketTypeParams struct {
	EventID           uuid.UUID `json:"event_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	Price             int32     `json:"price"`
	QuantityAvailable int32     `json:"quantity_available"`
	IsActive          *bool     `json:"is_active"`
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.QuantityAvailable,
		arg.IsActive,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.QuantityAvailable,
		&i.QuantitySold,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
