// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (event_id, name, description, price, quantity_available, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, name, description, price, quantity_available, quantity_sold, is_active, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID           uuid.UUID `json:"event_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	Price             int32     `json:"price"`
	QuantityAvailable int32     `json:"quantity_available"`
	IsActive          *bool     `json:"is_active"`
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.QuantityAvailable,
		arg.IsActive,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.QuantityAvailable,
		&i.QuantitySold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicketType = `-- name: DeleteTicketType :exec
DELETE FROM ticket_types WHERE id = $1 AND event_id = $2
`

type DeleteTicketTypeParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) DeleteTicketType(ctx context.Context, arg DeleteTicketTypeParams) error {
	_, err := q.db.Exec(ctx, deleteTicketType, arg.ID, arg.EventID)
	return err
}

const getTicketTypeByID = `-- name: GetTicketTypeByID :one
SELECT id, event_id, name, description, price, quantity_available, quantity_sold, is_active, created_at, updated_at FROM ticket_types WHERE id = $1
`

func (q *Queries) GetTicketTypeByID(ctx context.Context, id uuid.UUID) (TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeByID, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.QuantityAvailable,
		&i.QuantitySold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypesByEvent = `-- name: GetTicketTypesByEvent :many
SELECT id, event_id, name, description, price, quantity_available, quantity_sold, is_active, created_at, updated_at FROM ticket_types WHERE event_id = $1 ORDER BY price ASC
`

func (q *Queries) GetTicketTypesByEvent(ctx context.Context, eventID uuid.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, getTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.QuantityAvailable,
			&i.QuantitySold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE ticket_types
SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    price = COALESCE($5, price),
    quantity_available = COALESCE($6, quantity_available),
    is_active = COALESCE($7, is_active)
WHERE id = $1 AND event_id = $2
RETURNING id, event_id, name, description, price, quantity_available, quantity_sold, is_active, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	ID                uuid.UUID `json:"id"`
	EventID           uuid.UUID `json:"event_id"`
	Name              *string   `json:"name"`
	Description       string    `json:"description"`
	Price             *int32    `json:"price"`
	QuantityAvailable *int32    `json:"quantity_available"`
	IsActive          *bool     `json:"is_active"`
}

func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, updateTicketType,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.QuantityAvailable,
		arg.IsActive,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.QuantityAvailable,
		&i.QuantitySold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
